### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Andsoeg** [raulrene/twitter-contest-js-bot#23]
twitter-contest-js-bot-master>node index.js
Error retrieving blocked users: 400 - {"errors":[{"code":215,"message":"Bad Authentication data."}]}

**Comment by raulrene** [comment]
Hi @Andsoeg . That's the first API call to Twitter that's being done. Bad Authentication data means your auth. data is not valid. See the [config.js file](https://github.com/raulrene/twitter-contest-js-bot/blob/master/config.js)
