### ISSUE TITLE
ES6 issues

### ISSUE THREAD

**Issue by Designer023** [raulrene/twitter-contest-js-bot#30]
Hi,

I've been trying to get the new version working and it's thorwing some issues. Putting a "use strict"; fixed some of them, but then I'm getting a error in api-functions.js:22:

    const {text, count = 100, result_type = 'popular', since_id = 0, max_id, geocode} = options;
    SyntaxError: Unexpected token {

I would try and fix it myself but I'm new to using Es6 and don't want to break other spects of the bot by trying!

Thanks

**Comment by raulrene** [comment]
Hey there @Designer023 .

What's the node version you're running? Try a `node -v` in the console and consider updating to a more recent version.

Also, you could try running node with the --harmony flag: `node --harmony index.js` without the need to update.

Node implemented gradually the ES6 support and you should be running a more recent version. Please let me know if you manage to get it running. `6.9.5` is the latest stable version. Anything above `6.0.0` should work fine without the --harmony flag.
