### ISSUE TITLE
Can it recognise if the tweet saids "tag 2 friends" and do it?

### ISSUE THREAD

**Issue by FinleyCorrigan** [raulrene/twitter-contest-js-bot#35]

**Comment by raulrene** [comment]
Hi @FinleyCorrigan ,

Searching for those tweets should work by setting the `SEARCH_QUERIES` property in the [config.json](https://github.com/raulrene/twitter-contest-js-bot/blob/master/config.js) file, or by setting the `text` property when searching.

However tagging isn't implemented. If the Twitter API supports it and you have the time, feel free to add a PR with the Tag Method and we can integrate it. Theoretically it isn't a big deal implementation-wise, but as I've stated in the ReadMe file I'm not actively maintaining this repository.
