### ISSUE TITLE
[Error] { StatusCodeError: 429 - {"errors":[{"message":"Rate limit exceeded","code":88}]}

### ISSUE THREAD

**Issue by sebflex** [raulrene/twitter-contest-js-bot#39]
[Error] { StatusCodeError: 429 - {"errors":[{"message":"Rate limit exceeded","code":88}]}

This error way too often???

**Comment by raulrene** [comment]
Hi @sebflex , well, that's bc the Twitter API limits requests. Can't do much about it. You can increase the timeout so it will try less often
