### ISSUE TITLE
A way to block specific phrases

### ISSUE THREAD

**Issue by Zen00** [raulrene/twitter-contest-js-bot#4]
Sometimes people have "spam" retweets that follow specific patterns. I know that you can put -keyword into the API.search text field, however can you make a seperate field that you can enter in phrases or keywords you don't want to show up, to clear up the clutter in the section with words that you want to show up.

**Comment by raulrene** [comment]
@Zen00 , this sounds like an easy to do fix. I'll take a look over this soon. Sorry for not being very cooperative, but I have a lot on my schedule right now. If you know anyone that is willing to give a hand, that'd be great.
