### ISSUE TITLE
More SEARCH_QUERIES: or FILTERS: maybe?

### ISSUE THREAD

**Issue by sebflex** [raulrene/twitter-contest-js-bot#40]
Well I looked into different Twitter contest bots and I think we could add more filters into this one by default hm?

Stuff I added for mine(it's from the python bot I think):
       ```
 '#giveaway',
	'Retweet and win',
	'retweet and you could win', 
	'rt for your chance to win',
	'#giveawayalert',
	'win rt',
	'#rttowin',
	'#sweepstakes'
```

**Comment by raulrene** [comment]
Hello @sebflex ,

If you check the Readme you'll see you can customise the `SEARCH_QUERIES ` and `SEARCH_QUERY_FILTERS` any way you like (and many more things except that).

**Comment by sebflex** [comment]
> Hello @sebflex ,
> 
> If you check the Readme you'll see you can customise the `SEARCH_QUERIES ` and `SEARCH_QUERY_FILTERS` any way you like (and many more things except that).

Would you say it's worth adding other filter words etc? Did you have a customized version that you can share?
