### ISSUE TITLE
error 220

### ISSUE THREAD

**Issue by calvin2000001** [raulrene/twitter-contest-js-bot#42]
Can't get past this part on running:

 toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     body:
      '{"errors":[{"message":"Your credentials do not allow access to this resource","code":220}]}' } }

**Comment by calvin2000001** [comment]
I am using mavericks still 10.9.5.

**Comment by raulrene** [comment]
Hi @calvin2000001 ,

I don't think this is an issue with the bot, but rather with your setup. It appears you didn't manage the Twitter Token correctly. Check this link for reference: https://twittercommunity.com/t/i-keep-get-your-credentials-do-not-allow-access-to-this-resource-when-i-try-to-destroy-friendships-what-am-i-missing/12249/2
