### ISSUE TITLE
Geolocation

### ISSUE THREAD

**Issue by Zen00** [raulrene/twitter-contest-js-bot#5]
I'd prefer to not be entering contests in Sweden, because I won a free lunch at some Swedish restaurant and can't cash in. :(

Any way to geo-filter?

**Comment by ps6000** [comment]
Congratulations on the Swedish lunch, I am not sure how you would do this with the geolocation, but you might be able to do something with the API search. 

Maybe a variable could be added in the config where you have a list of possible name variations for your city. Then it calls the name in the API search. My thought is below. Please note that I know nothing of the twitter API...

old
text: "retweet to win -vote -filter:retweets OR RT to win -vote -filter:retweets", 
new thought
text: "(retweet to win -vote -filter:retweets OR RT to win -vote -filter:retweets) AND + <location name>",

**Comment by raulrene** [comment]
As per the current Twitter API, there seems to be a way to filter by Geolocation. Marked as an enhacement
