### ISSUE TITLE
Tweeting Too Fast

### ISSUE THREAD

**Issue by Zen00** [raulrene/twitter-contest-js-bot#7]
Apparently Twitter decided that my app was a spam bot because of too much tweeting so decided to shut it down.

So anyways, I hope that as we keep trying to improve the filters for this app it won't run into this problem in the future.

Maybe we should consider slowing down the rate that it retweets at, plus the geo-filtering to reduce the amount of material, as well as better filters against useless retweets.

**Comment by henhouse** [comment]
Seems like the Python brother of this script has recently implemented rate limits as well to prevent the script from being seen as spam. Hopefully that'll be done here too.

**Comment by ps6000** [comment]
How long til it was blocked?

**Comment by raulrene** [comment]
@Zen00 @ps6000 , I know this is an old issue. If you have any suggestions for the timeout let me know. I can make it configurable at runtime if not

**Comment by raulrene** [comment]
With #27 I've rewritten the bot with ES6. I've also made some changes to the flow. More to come, as I don't really like the setTimeout method of waiting right now. But in the meanwhile, in the **config.js** file there is a RATE_SEARCH_TIMEOUT field - currently set to 15 seconds. It can be updated by everyone specific to their needs.
